export const tools = [
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, and paragraphs in real-time.",
    category: "writing",
    url: "./word-counter.html",
    icon: "📝",
    keywords: ["word count", "character count", "essay length", "writing tool"],
  },

  {
    id: "case-converter",
    name: "Case Converter",
    description:
      "Convert text between Content Case, uppercase, lowercase, and more.",
    category: "formatting",
    url: "./case-converter.html",
    icon: "Aa",
    keywords: ["uppercase", "lowercase", "capitalization", "title case"],
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Beautify and validate JSON code.",
    category: "developer",
    url: "./json-formatter.html",
    icon: "{}",
    keywords: ["json pretty", "json validate", "json lint", "pretty print"],
  },
  {
    id: "text-cleaner",
    name: "Text Cleaner",
    description: "Remove spaces, duplicate lines, emojis, and normalize text.",
    category: "formatting",
    url: "./text-cleaner.html",
    icon: "🧹",
    keywords: [
      "clean text",
      "remove spaces",
      "remove emojis",
      "normalize",
      "trim",
    ],
  },
  {
    id: "find-replace",
    name: "Find & Replace",
    description:
      "Search, highlight, extract patterns, and filter lines using Regex.",
    category: "developer",
    url: "./find-replace.html",
    icon: "🔍",
    keywords: [
      "regex",
      "grep",
      "filter lines",
      "extract text",
      "find and replace",
      "search",
    ],
  },
  {
    id: "base64-encode",
    name: "Base64 Encoder",
    description: "Encode and decode Base64 strings instantly.",
    category: "developer",
    url: "./base64-encode.html",
    icon: "🔤",
    keywords: ["base64 encode", "base64 decode", "b64"],
  },
  {
    id: "url-encode",
    name: "URL Encoder",
    description: "Encode/Decode URLs and special characters.",
    category: "developer",
    url: "./url-encode.html",
    icon: "🔗",
    keywords: ["url encode", "percent encoding", "decode url"],
  },
  {
    id: "html-encode",
    name: "HTML Encoder",
    description: "Convert characters to HTML entities to prevent XSS.",
    category: "developer",
    url: "./html-encode.html",
    icon: "💻",
    keywords: ["html entity", "escape html", "sanitize text"],
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate SHA-256, SHA-512, and MD5 hashes.",
    category: "security",
    url: "./hash-generator.html",
    icon: "🛡️",
    keywords: ["sha256", "sha1", "md5", "checksum", "hash generator"],
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode JSON Web Tokens to view claims.",
    category: "security",
    url: "./jwt-decoder.html",
    icon: "🔑",
    keywords: ["jwt decode", "json web token", "token viewer"],
  },
  {
    id: "password-strength",
    name: "Password Checker",
    description: "Test password strength and entropy.",
    category: "security",
    url: "./password-strength.html",
    icon: "💪",
    keywords: ["password strength", "entropy", "password test"],
  },
  {
    id: "text-ciphers",
    name: "Text Ciphers",
    description: "Encrypt text with ROT13, Caesar Cipher, and Obfuscator.",
    category: "security",
    url: "./text-ciphers.html",
    icon: "🕵️",
    keywords: ["rot13", "caesar cipher", "obfuscate text", "encryption"],
  },
  {
    id: "json-format",
    name: "JSON Formatter",
    description: "Beautify and indent JSON data.",
    category: "formatter",
    url: "./json-format.html",
    icon: "🎨",
    keywords: ["json pretty", "json beautify", "format json"],
  },
  {
    id: "json-minify",
    name: "JSON Minifier",
    description: "Compress JSON by removing whitespace.",
    category: "formatter",
    url: "./json-minify.html",
    icon: "📦",
    keywords: ["json compress", "minify json", "json smaller"],
  },
  {
    id: "json-validate",
    name: "JSON Validator",
    description: "Check if JSON is valid and find errors.",
    category: "formatter",
    url: "./json-validate.html",
    icon: "✅",
    keywords: ["json lint", "json check", "validate json"],
  },
  {
    id: "json-csv",
    name: "JSON to CSV",
    description: "Convert JSON arrays to CSV format.",
    category: "converter",
    url: "./json-to-csv.html",
    icon: "📊",
    keywords: ["json to csv", "json excel", "convert json"],
  },
  {
    id: "csv-json",
    name: "CSV to JSON",
    description: "Convert CSV data to JSON array.",
    category: "converter",
    url: "./csv-to-json.html",
    icon: "📋",
    keywords: ["csv to json", "csv convert", "spreadsheet json"],
  },
  {
    id: "xml-format",
    name: "XML Formatter",
    description: "Beautify and indent XML data.",
    category: "formatter",
    url: "./xml-format.html",
    icon: "📄",
    keywords: ["xml pretty", "xml beautify", "format xml"],
  },
  {
    id: "xml-minify",
    name: "XML Minifier",
    description: "Compress XML by removing whitespace.",
    category: "formatter",
    url: "./xml-minify.html",
    icon: "🗜️",
    keywords: ["xml compress", "minify xml"],
  },
  {
    id: "yaml-format",
    name: "YAML Formatter",
    description: "Clean up YAML indentation.",
    category: "formatter",
    url: "./yaml-format.html",
    icon: "📝",
    keywords: ["yaml pretty", "yaml indent", "format yaml"],
  },
  {
    id: "yaml-json",
    name: "YAML to JSON",
    description: "Convert YAML to JSON format.",
    category: "converter",
    url: "./yaml-to-json.html",
    icon: "🔄",
    keywords: ["yaml to json", "yaml convert"],
  },
  {
    id: "md-format",
    name: "Markdown Formatter",
    description: "Normalize Markdown headers and lists.",
    category: "formatter",
    url: "./markdown-format.html",
    icon: "📝",
    keywords: ["markdown pretty", "md format"],
  },
  {
    id: "md-html",
    name: "Markdown to HTML",
    description: "Convert Markdown to HTML code.",
    category: "converter",
    url: "./markdown-to-html.html",
    icon: "🔀",
    keywords: ["md to html", "markdown html"],
  },
  {
    id: "html-md",
    name: "HTML to Markdown",
    description: "Convert HTML to Markdown format.",
    category: "converter",
    url: "./html-to-markdown.html",
    icon: "⬅️",
    keywords: ["html to md", "html markdown"],
  },
  {
    id: "sql-format",
    name: "SQL Formatter",
    description: "Beautify SQL queries with proper keywords.",
    category: "formatter",
    url: "./sql-format.html",
    icon: "🗃️",
    keywords: ["sql pretty", "sql beautify", "format sql"],
  },
  {
    id: "log-format",
    name: "Log Formatter",
    description: "Align log timestamps for easier reading.",
    category: "formatter",
    url: "./log-format.html",
    icon: "📜",
    keywords: ["log align", "log pretty", "format logs"],
  },
  {
    id: "uuid-gen",
    name: "UUID Generator",
    description: "Generate random UUID v4 identifiers.",
    category: "generator",
    url: "./uuid-generator.html",
    icon: "🆔",
    keywords: ["uuid", "guid", "unique id", "random id"],
  },
  {
    id: "slug-gen",
    name: "Slug Generator",
    description: "Convert text to URL-friendly slugs.",
    category: "generator",
    url: "./slug-generator.html",
    icon: "🔗",
    keywords: ["slug", "url slug", "seo url", "permalink"],
  },
  {
    id: "lorem-gen",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text for designs.",
    category: "generator",
    url: "./lorem-ipsum.html",
    icon: "📝",
    keywords: ["lorem ipsum", "placeholder text", "dummy text"],
  },
  {
    id: "random-text",
    name: "Random Text Generator",
    description: "Create random strings with custom character sets.",
    category: "generator",
    url: "./random-text.html",
    icon: "🎲",
    keywords: ["random string", "random text", "password generator", "token"],
  },
  {
    id: "meta-title",
    name: "Meta Title Checker",
    description: "Check your title tag length for SEO.",
    category: "seo",
    url: "./meta-title-checker.html",
    icon: "🏷️",
    keywords: ["meta title", "title tag", "seo title", "title length"],
  },
  {
    id: "meta-desc",
    name: "Meta Description Checker",
    description: "Optimize your meta description length.",
    category: "seo",
    url: "./meta-desc-checker.html",
    icon: "📋",
    keywords: ["meta description", "seo description", "description length"],
  },
  {
    id: "keyword-extract",
    name: "Keyword Extractor",
    description: "Extract important keywords from text.",
    category: "seo",
    url: "./keyword-extractor.html",
    icon: "🔑",
    keywords: ["keyword extractor", "extract keywords", "seo keywords"],
  },
  {
    id: "keyword-freq",
    name: "Keyword Frequency",
    description: "Analyze keyword density and distribution.",
    category: "seo",
    url: "./keyword-frequency.html",
    icon: "📊",
    keywords: ["keyword density", "keyword frequency", "word frequency"],
  },
  {
    id: "ngram-gen",
    name: "N-gram Generator",
    description: "Generate bigrams and trigrams from text.",
    category: "seo",
    url: "./ngram-generator.html",
    icon: "🔗",
    keywords: ["ngram", "bigram", "trigram", "word pairs"],
  },
  {
    id: "serp-preview",
    name: "SERP Snippet Preview",
    description: "Preview how your page appears in Google.",
    category: "seo",
    url: "./serp-preview.html",
    icon: "🔍",
    keywords: ["serp preview", "google preview", "snippet preview"],
  },
  {
    id: "heading-analyzer",
    name: "Heading Analyzer",
    description: "Check your H1-H6 heading structure.",
    category: "seo",
    url: "./heading-analyzer.html",
    icon: "📝",
    keywords: ["heading structure", "h1 checker", "heading hierarchy"],
  },
  {
    id: "content-score",
    name: "Content Score",
    description: "Evaluate content quality for SEO.",
    category: "seo",
    url: "./content-score.html",
    icon: "🏆",
    keywords: ["content score", "content quality", "seo score"],
  },
  {
    id: "readability-seo",
    name: "Readability Checker",
    description: "Calculate Flesch reading ease for SEO.",
    category: "seo",
    url: "./readability-checker.html",
    icon: "📖",
    keywords: ["readability", "flesch score", "reading level", "grade level"],
  },
  {
    id: "diff-view",
    name: "Diff View",
    description: "Compare two texts with highlighted differences.",
    category: "compare",
    url: "./diff-view.html",
    icon: "📝",
    keywords: ["diff", "compare text", "text difference", "code compare"],
  },
  {
    id: "side-compare",
    name: "Side-by-Side Compare",
    description: "Compare documents in side-by-side view.",
    category: "compare",
    url: "./side-compare.html",
    icon: "📊",
    keywords: [
      "side by side",
      "compare documents",
      "text compare",
      "dual view",
    ],
  },
  {
    id: "clock",
    name: "Digital Clock",
    description: "Beautiful full-screen digital clock with real-time display.",
    category: "utility",
    url: "./clock.html",
    icon: "⏰",
    keywords: [
      "clock",
      "time",
      "digital clock",
      "timer",
      "date",
      "fullscreen clock",
    ],
  },
  {
    id: "what-is-my-ip-address",
    name: "What is My IP",
    description:
      "Find your public IP address instantly. Check IPv4, IPv6, location, ISP, and browser details.",
    category: "network",
    url: "./what-is-my-ip-address.html",
    icon: "🌐",
    keywords: [
      "what is my ip",
      "what is my ip address",
      "my ip address",
      "ip address",
      "ip lookup",
      "public ip",
      "ip checker",
      "my ip",
      "check my ip",
      "find my ip",
      "show my ip",
      "ipv4",
      "ipv6",
    ],
  },
];

export const searchTools = (query) => {
  const lowerQuery = query.toLowerCase();
  return tools.filter(
    (tool) =>
      tool.name.toLowerCase().includes(lowerQuery) ||
      tool.description.toLowerCase().includes(lowerQuery) ||
      tool.keywords.some((k) => k.includes(lowerQuery)),
  );
};
